language: node_js
node_js:
- 12.1.0
cache: npm
before_cache:
- rm -rf $HOME/.npm/_logs
git:
  quiet: true
  submodules: false

before_install:
- openssl aes-256-cbc -K $encrypted_062b79b4d9f7_key -iv $encrypted_062b79b4d9f7_iv
  -in lazyassdevs-key-pair-useast2.pem.enc -out lazyassdevs-key-pair-useast2.pem -d
- chmod 600 lazyassdevs-key-pair-useast2.pem && mv lazyassdevs-key-pair-useast2.pem ~/.ssh/id_rsa
- ssh-keyscan -H 13.58.240.217 >> ~/.ssh/known_hosts

deploy:
  skip_cleanup: true
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
